services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    build:
      target: development
    volumes:
      - ..:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
